import type { Config } from '@shared/types'
import { DEFAULT_BINDINGS } from '@shared/types'
import { CarType, HandDriveType, PhoneWorkMode } from '@shared/types/Config'
import {
  DEFAULT_PLAYLIST_DIRECTORY,
  DEFAULT_ROM_DIRECTORY,
  DEFAULT_THUMBNAIL_DIRECTORY
} from '@shared/types/Games'

export const DEFAULT_CONFIG: Config = {
  dismissedPackages: [],
  updateNightly: false,
  projectionWidth: 1280,
  projectionHeight: 720,
  projectionFps: 60,
  projectionDpi: 0,
  projectionViewAreaTop: 0,
  projectionViewAreaBottom: 0,
  projectionViewAreaLeft: 0,
  projectionViewAreaRight: 0,
  projectionSafeAreaTop: 0,
  projectionSafeAreaBottom: 0,
  projectionSafeAreaLeft: 0,
  projectionSafeAreaRight: 0,
  projectionSafeAreaDrawOutside: true,
  clusterWidth: 1280,
  clusterHeight: 720,
  clusterFps: 60,
  clusterDpi: 0,
  clusterViewAreaTop: 0,
  clusterViewAreaBottom: 0,
  clusterViewAreaLeft: 0,
  clusterViewAreaRight: 0,
  clusterSafeAreaTop: 60,
  clusterSafeAreaBottom: 10,
  clusterSafeAreaLeft: 300,
  clusterSafeAreaRight: 300,
  lastConnectedAaBtMac: '',
  lastPhoneWorkMode: PhoneWorkMode.CarPlay,
  carName: 'LIVI',
  oemName: 'App',
  darkMode: true,
  nightMode: true,
  hand: HandDriveType.LHD,
  samplingFrequency: 1,
  autoConn: true,
  UseBTPhone: false,
  disableAudioOutput: false,
  wifiType: '5ghz',
  wifiChannel: 36,
  country: 'DE',
  phoneConfig: {},
  carType: CarType.Gasoline,
  evConnectorTypes: [],
  wirelessAaEnabled: false,
  wirelessCpEnabled: false,
  wifiPassword: '12345678',
  btAdapter: 'hci0',
  wifiInterface: 'wlan0',
  wifiDedicatedInterface: false,
  carPlaySourceVersion: '950.7.1',
  carPlayMfiI2cBus: 2,
  carPlayMfiPowerGpio: 21,
  appearanceMode: 'auto',
  displayMode: '',
  displayGamma: 1.0,
  displayContrast: 1.0,
  displayColorR: 1.0,
  displayColorG: 1.0,
  displayColorB: 1.0,
  startPage: 'home',
  language: 'en',
  games: {
    enabled: false,
    retroArchPath: 'retroarch',
    romDirectory: DEFAULT_ROM_DIRECTORY,
    playlistDirectory: DEFAULT_PLAYLIST_DIRECTORY,
    thumbnailDirectory: DEFAULT_THUMBNAIL_DIRECTORY
  },
  minidsp: {
    enabled: true,
    mockDevice: false,
    serverUrl: 'http://127.0.0.1:5380',
    deviceIndex: 0,
    volumeMinDb: -80,
    volumeMaxDb: 0,
    volumeStepDb: 0.5,
    bassOutputChannels: [2, 3],
    bassGainDb: 0,
    bassMinDb: -80,
    bassMaxDb: 12,
    bassStepDb: 0.5,
    presets: [
      { index: 0, label: 'Preset 1' },
      { index: 1, label: 'Preset 2' },
      { index: 2, label: 'Preset 3' },
      { index: 3, label: 'Preset 4' }
    ]
  },
  kiosk: { main: false, dash: false, aux: false },
  uiZoomPercent: 100,
  cameraId: '',
  camera: { main: true, dash: false, aux: false },
  cameraMirror: false,
  cameraRotation: 0,
  autoSwitchOnReverse: true,
  dongleToolsIp: '',
  visualAudioDelayMs: 0,
  huVolume: 0.95,
  huVolumeLinkSystem: true,
  audioVolume: 0.95,
  navVolume: 0.95,
  voiceAssistantVolume: 0.95,
  callVolume: 0.95,
  systemSoundsVolume: 0.75,
  audioOutputDevice: '',
  audioOutputDeviceLabel: '',
  audioInputDevice: '',
  audioInputDeviceLabel: '',
  primaryColorDark: '',
  highlightColorDark: '',
  primaryColorLight: '',
  highlightColorLight: '',
  backgroundColorDark: '',
  backgroundColorLight: '',
  mainScreenWidth: 1280,
  mainScreenHeight: 720,
  dashScreenActive: false,
  dashScreenWidth: 1280,
  dashScreenHeight: 720,
  auxScreenActive: false,
  auxScreenWidth: 800,
  auxScreenHeight: 480,
  mainScreenBounds: { x: 0, y: 0, width: 0, height: 0 },
  dashScreenBounds: { x: 0, y: 0, width: 0, height: 0 },
  auxScreenBounds: { x: 0, y: 0, width: 0, height: 0 },
  dashboards: {
    dash1: { main: true, dash: false, aux: false, pos: 1 },
    dash2: { main: true, dash: false, aux: false, pos: 2 },
    dash3: { main: true, dash: false, aux: false, pos: 3 },
    dash4: { main: true, dash: false, aux: false, pos: 4 }
  },
  media: { main: true, dash: false, aux: false },
  bindings: DEFAULT_BINDINGS,
  dongleIcon120: '',
  dongleIcon180: '',
  dongleIcon256: ''
}
